version: "3.8"

services:
  frontend:
    build:
      context: ./twitch-nakrutka
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - db

  backend:
    build:
      context: ./twitch-nakrutka-backend
      dockerfile: Dockerfile
    ports:
      - "4444:4444"
    environment:
      - DATABASE_URL=postgres://postgres:root@db:5432/twitch
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: twitch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
