# Указываем базовый образ Node.js
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем package.json и package-lock.json (если есть)
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы приложения
COPY . .

# Открываем порт
EXPOSE 4444

# Команда для запуска вашего приложения
CMD ["npm", "run", "start:dev"]
